FROM openjdk:11-jre
ADD ./dist/userMicroservice-1.0.jar app.jar
RUN bash -c 'touch /app.jar'
# ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Dserver.port=$PORT","-jar","/app.jar"]
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]